{"Launchpad":"https://bugs.launchpad.net/bugs/1276510","Id":"1276510","Gerrit":"https://review.openstack.org/72665","IdGerrit":"72665","IdCommit":"d043874cef9a783b89226e8462e50465de31d117","Files":["cinder/openstack/common/db/sqlalchemy/session.py"],"Lines_Inseted":1,"Lines_Deleted":1,"CommitParent":"41f043a6241890d04758dad7caa1c54fae92a964","Classification":"Not_Bug","KeywordsTitle":" lost connection being raised","Description":"code error is not in the list of connection lost issues,  reconnect loop, error, stop retrying, OperationalError, system error","KeywordsCommit":"","Comments":"the description of the commit indicates that this is not a bug."}