{"Launchpad":"https://bugs.launchpad.net/bugs/1496694","Id":"1496694","Gerrit":"https://review.openstack.org/225024","IdGerrit":"225024","IdCommit":"d75d04ec55f906de5f90d186881bac25688a906b","Files":["cinder/db/sqlalchemy/api.py","cinder/tests/unit/test_db_api.py"],"Lines_Inseted":6,"Lines_Deleted":5,"CommitParent":"47b93189f30c66925aa7b5acd1d6f6ec4212ea0a","Classification":"Not_Bug","KeywordsTitle":"case sensitivity problem","Description":"failed","KeywordsCommit":"","Comments":"caused by the difference of handling of case sensitivity for backend name"}