{"Launchpad":"https://bugs.launchpad.net/bugs/1508889","Id":"","Gerrit":"https://review.openstack.org/238487","IdCommit":"288ca5d8d6384926c2c3b2cb84b02be843846d2d","Files":["cinder/locale/cinder-log-error.pot","cinder/locale/cinder-log-info.pot","cinder/locale/cinder-log-warning.pot","cinder/locale/cinder.pot","cinder/locale/tr_TR/LC_MESSAGES/cinder.po","cinder/tests/unit/test_emc_vmax.py","cinder/tests/unit/test_huawei_drivers.py","cinder/tests/unit/volume/drivers/netapp/dataontap/client/test_api.py","cinder/volume/drivers/emc/emc_vmax_common.py","cinder/volume/drivers/netapp/dataontap/client/api.py"],"Lines_Inseted":1,"Lines_Deleted":1169,"CommitParent":"b22c3d695beb375aca99f28941c0a19d66815b26","Classification":"Bug","KeywordsTitle":"inconsistently,should be changed","Description":"","KeywordsCommit":"wrong behaviour","Comments":"could not get all the info from the cinder repo."}
