{"Launchpad":"https://bugs.launchpad.net/bugs/1513263","Id":"1513263","Gerrit":"https://review.openstack.org/241999","IdGerrit":"241999","IdCommit":"b4a41cf44b664587f4175ceaa9a673eefc6f8191","Files":["cinder/tests/unit/test_cmd.py"],"Lines_Inseted":0,"Lines_Deleted":0,"CommitParent":"e4c3ca5c6c7fe02fc63ec2952c31850d7ff13d0a","Classification":"Not_Bug","KeywordsTitle":"fails","Description":"always failed","KeywordsCommit":"fix failure of unit test","Comments":"the only file influenced by this problem is a test file."}